import { useCallback, useEffect, useRef, useState } from "react";
import type { Color, Role } from "./colors";
import type { TurnOutcome } from "./matchTypes";
import { attemptSoloPress, generateSoloSequence, sequenceLengthForRound } from "./soloEngine";

// Mirrors server/src/rooms/MatchRoom.ts's DEFAULT_TURN_DURATION_MS.
const TURN_DURATION_MS = 4000;

export function useSoloMatch(role: Role) {
  const [round, setRound] = useState(1);
  const [sequence, setSequence] = useState<Color[]>(() =>
    generateSoloSequence(sequenceLengthForRound(1), Math.random, role),
  );
  const [cursor, setCursor] = useState(0);
  const [turnOutcome, setTurnOutcome] = useState<TurnOutcome>("pending");
  const [turnEndsAt, setTurnEndsAt] = useState(() => Date.now() + TURN_DURATION_MS);

  const roundRef = useRef(1);
  const turnDecidedRef = useRef(false);
  const turnTokenRef = useRef(0);
  const timeoutIdRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // press() must judge against the true current sequence/cursor even when a
  // second press fires before React has re-rendered from the first (e.g.
  // two taps landing in the same event-loop turn) — reading the `sequence`/
  // `cursor` state closures directly can still see the pre-press values in
  // that window, misjudging an objectively-correct second press as wrong.
  // Refs stay synchronously accurate across rapid calls the same way
  // turnDecidedRef already does above.
  const sequenceRef = useRef(sequence);
  const cursorRef = useRef(cursor);

  function scheduleExpiry() {
    if (timeoutIdRef.current !== null) clearTimeout(timeoutIdRef.current);
    turnTokenRef.current += 1;
    const token = turnTokenRef.current;
    timeoutIdRef.current = setTimeout(() => {
      if (token === turnTokenRef.current) onTimerExpired();
    }, TURN_DURATION_MS);
  }

  function startTurn(nextRound: number) {
    roundRef.current = nextRound;
    setRound(nextRound);
    const nextSequence = generateSoloSequence(sequenceLengthForRound(nextRound), Math.random, role);
    sequenceRef.current = nextSequence;
    cursorRef.current = 0;
    setSequence(nextSequence);
    setCursor(0);
    setTurnOutcome("pending");
    setTurnEndsAt(Date.now() + TURN_DURATION_MS);
    turnDecidedRef.current = false;
    scheduleExpiry();
  }

  function onTimerExpired() {
    if (!turnDecidedRef.current) {
      turnDecidedRef.current = true;
      setTurnOutcome("fail");
    }
    // timeout means nothing is left to hold on screen — hand off right away,
    // same as MatchRoom.onTurnTimerExpired.
    startTurn(roundRef.current + 1);
  }

  useEffect(() => {
    // Arms the timer for the very first turn (already generated by the
    // useState initializers above) — startTurn() itself arms the timer for
    // every subsequent round.
    scheduleExpiry();
    return () => {
      if (timeoutIdRef.current !== null) clearTimeout(timeoutIdRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Stable across renders (empty deps) — press only ever touches refs and
  // setState setters, both stable by construction, so it never actually
  // needs to change identity. Lets ButtonPanel be React.memo'd effectively
  // (a fresh function reference every render would defeat that memo just
  // as much as not memoizing at all) — see ButtonPanel.tsx.
  const press = useCallback((color: Color) => {
    if (turnDecidedRef.current) return;

    const result = attemptSoloPress(sequenceRef.current, cursorRef.current, color);
    if (!result.correct) {
      turnDecidedRef.current = true;
      setTurnOutcome("fail");
      // Wrong press holds the fail state on screen until the original 4s
      // mark (scheduleExpiry's pending timeout), same as
      // MatchRoom.handlePressButton.
      return;
    }

    cursorRef.current = result.nextCursor;
    setCursor(result.nextCursor);
    if (result.complete) {
      turnDecidedRef.current = true;
      setTurnOutcome("success");
      // Turn hand-off is deferred to the already-armed scheduleExpiry timeout
      // (onTimerExpired), same as the wrong-press path above — calling
      // startTurn() synchronously here would batch its setTurnOutcome("pending")
      // together with this one, so "success" would never actually render.
      // Mirrors MatchRoom.handlePressButton on the server.
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- only refs/setState setters used, both stable
  }, []);

  return { round, sequence, cursor, turnOutcome, turnEndsAt, press };
}
