import { useEffect, useRef, useState } from "react";
import type { Color, Role } from "./colors";
import type { TurnOutcome } from "./matchTypes";
import { attemptSoloPress, generateSoloSequence, sequenceLengthForRound } from "./soloEngine";

// Mirrors server/src/rooms/MatchRoom.ts's DEFAULT_TURN_DURATION_MS.
const TURN_DURATION_MS = 4000;

export function useSoloMatch(role: Role) {
  const [round, setRound] = useState(1);
  const [sequence, setSequence] = useState<Color[]>(() =>
    generateSoloSequence(sequenceLengthForRound(1), Math.random, role),
  );
  const [cursor, setCursor] = useState(0);
  const [turnOutcome, setTurnOutcome] = useState<TurnOutcome>("pending");
  const [turnEndsAt, setTurnEndsAt] = useState(() => Date.now() + TURN_DURATION_MS);

  const roundRef = useRef(1);
  const turnDecidedRef = useRef(false);
  const turnTokenRef = useRef(0);
  const timeoutIdRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  function scheduleExpiry() {
    if (timeoutIdRef.current !== null) clearTimeout(timeoutIdRef.current);
    turnTokenRef.current += 1;
    const token = turnTokenRef.current;
    timeoutIdRef.current = setTimeout(() => {
      if (token === turnTokenRef.current) onTimerExpired();
    }, TURN_DURATION_MS);
  }

  function startTurn(nextRound: number) {
    roundRef.current = nextRound;
    setRound(nextRound);
    setSequence(generateSoloSequence(sequenceLengthForRound(nextRound), Math.random, role));
    setCursor(0);
    setTurnOutcome("pending");
    setTurnEndsAt(Date.now() + TURN_DURATION_MS);
    turnDecidedRef.current = false;
    scheduleExpiry();
  }

  function onTimerExpired() {
    if (!turnDecidedRef.current) {
      turnDecidedRef.current = true;
      setTurnOutcome("fail");
    }
    // timeout means nothing is left to hold on screen — hand off right away,
    // same as MatchRoom.onTurnTimerExpired.
    startTurn(roundRef.current + 1);
  }

  useEffect(() => {
    // Arms the timer for the very first turn (already generated by the
    // useState initializers above) — startTurn() itself arms the timer for
    // every subsequent round.
    scheduleExpiry();
    return () => {
      if (timeoutIdRef.current !== null) clearTimeout(timeoutIdRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function press(color: Color) {
    if (turnDecidedRef.current) return;

    const result = attemptSoloPress(sequence, cursor, color);
    if (!result.correct) {
      turnDecidedRef.current = true;
      setTurnOutcome("fail");
      // Wrong press holds the fail state on screen until the original 4s
      // mark (scheduleExpiry's pending timeout), same as
      // MatchRoom.handlePressButton.
      return;
    }

    setCursor(result.nextCursor);
    if (result.complete) {
      turnDecidedRef.current = true;
      setTurnOutcome("success");
      startTurn(roundRef.current + 1);
    }
  }

  return { round, sequence, cursor, turnOutcome, turnEndsAt, press };
}
